### ISSUE TITLE
Pull access denied for opencti-rf-feeds

### ISSUE THREAD

**Issue by NetEyes** [jbfeldman/opencti-taxxi2-connector#2]
after adding taxxi2 connector to the main opencti docker-compose.yml and run it again. I got the following error messages ..

"ERROR: pull access denied for opencti-rf-feeds, repository does not exist or may require 'docker login;  denied: requested access to the resources is denied."

![image](https://user-images.githubusercontent.com/20463433/105116336-8f431880-5a98-11eb-854d-7b1c69759c90.png)

**Comment by jbfeldman** [comment]
Hey @NetEyes, this is happening because I haven't pushed a base image to a docker registry like dockerhub (though that would be an excellent idea!). Before adding the connector to your docker-compose.yml, you'll need to build the docker image on the machine running OpenCTI as specified in the README. 

To build the docker image

1. Clone the repository
2. From the taxii2 directory, run `docker build . -t opencti-taxii2-import:latest`
3. Add the connector to your docker-compose.yml and spin up the stack
